:- [fullanswerMatosAramis].

phone(A):- atom_codes(A,[112]).
phone(A):- atom_codes(A,[098]).
phone(A):- atom_codes(A,[109]).
phone(A):- atom_codes(A,[116]).
phone(A):- atom_codes(A,[100]).
phone(A):- atom_codes(A,[110]).
phone(A):- atom_codes(A,[107]).
phone(A):- atom_codes(A,[103]).
phone(A):- atom_codes(A,[331]).
phone(A):- atom_codes(A,[102]).
phone(A):- atom_codes(A,[118]).
phone(A):- atom_codes(A,[952]).
phone(A):- atom_codes(A,[240]).
phone(A):- atom_codes(A,[115]).
phone(A):- atom_codes(A,[122]).
phone(A):- atom_codes(A,[643]).
phone(A):- atom_codes(A,[658]).
phone(A):- atom_codes(A,[269]).
phone(A):- atom_codes(A,[496]).
phone(A):- atom_codes(A,[108]).
phone(A):- atom_codes(A,[633]).
phone(A):- atom_codes(A,[106]).
phone(A):- atom_codes(A,[119]).
phone(A):- atom_codes(A,[104]).
phone(A):- atom_codes(A,[105]).
phone(A):- atom_codes(A,[618]).
phone(A):- atom_codes(A,[101]).
phone(A):- atom_codes(A,[230]).
phone(A):- atom_codes(A,[117]).
phone(A):- atom_codes(A,[650]).
phone(A):- atom_codes(A,[111]).
phone(A):- atom_codes(A,[097]).
phone(A):- atom_codes(A,[601]).
phone(A):- atom_codes(A,[652]).