:- [phone].
cns(A):- atom_codes(A,[112]).
cns(A):- atom_codes(A,[098]).
cns(A):- atom_codes(A,[109]).
cns(A):- atom_codes(A,[116]).
cns(A):- atom_codes(A,[100]).
cns(A):- atom_codes(A,[110]).
cns(A):- atom_codes(A,[107]).
cns(A):- atom_codes(A,[103]).
cns(A):- atom_codes(A,[331]).
cns(A):- atom_codes(A,[102]).
cns(A):- atom_codes(A,[118]).
cns(A):- atom_codes(A,[952]).
cns(A):- atom_codes(A,[240]).
cns(A):- atom_codes(A,[115]).
cns(A):- atom_codes(A,[122]).
cns(A):- atom_codes(A,[643]).
cns(A):- atom_codes(A,[658]).
cns(A):- atom_codes(A,[269]).
cns(A):- atom_codes(A,[496]).
cns(A):- atom_codes(A,[108]).
cns(A):- atom_codes(A,[633]).
cns(A):- atom_codes(A,[106]).
cns(A):- atom_codes(A,[119]).
cns(A):- atom_codes(A,[104]).
snt(A):- atom_codes(A,[109]).
snt(A):- atom_codes(A,[110]).
snt(A):- atom_codes(A,[331]).
snt(A):- atom_codes(A,[108]).
snt(A):- atom_codes(A,[633]).
snt(A):- atom_codes(A,[106]).
snt(A):- atom_codes(A,[119]).
snt(A):- atom_codes(A,[105]).
snt(A):- atom_codes(A,[618]).
snt(A):- atom_codes(A,[101]).
snt(A):- atom_codes(A,[230]).
snt(A):- atom_codes(A,[117]).
snt(A):- atom_codes(A,[650]).
snt(A):- atom_codes(A,[111]).
snt(A):- atom_codes(A,[097]).
snt(A):- atom_codes(A,[601]).
snt(A):- atom_codes(A,[652]).
nas(A):- atom_codes(A,[109]).
nas(A):- atom_codes(A,[110]).
nas(A):- atom_codes(A,[331]).
voi(A):- atom_codes(A,[098]).
voi(A):- atom_codes(A,[109]).
voi(A):- atom_codes(A,[100]).
voi(A):- atom_codes(A,[110]).
voi(A):- atom_codes(A,[103]).
voi(A):- atom_codes(A,[331]).
voi(A):- atom_codes(A,[118]).
voi(A):- atom_codes(A,[240]).
voi(A):- atom_codes(A,[122]).
voi(A):- atom_codes(A,[658]).
voi(A):- atom_codes(A,[496]).
voi(A):- atom_codes(A,[108]).
voi(A):- atom_codes(A,[633]).
voi(A):- atom_codes(A,[106]).
voi(A):- atom_codes(A,[119]).
voi(A):- atom_codes(A,[105]).
voi(A):- atom_codes(A,[618]).
voi(A):- atom_codes(A,[101]).
voi(A):- atom_codes(A,[230]).
voi(A):- atom_codes(A,[117]).
voi(A):- atom_codes(A,[650]).
voi(A):- atom_codes(A,[111]).
voi(A):- atom_codes(A,[097]).
voi(A):- atom_codes(A,[601]).
voi(A):- atom_codes(A,[652]).
cnt(A):- atom_codes(A,[102]).
cnt(A):- atom_codes(A,[118]).
cnt(A):- atom_codes(A,[952]).
cnt(A):- atom_codes(A,[240]).
cnt(A):- atom_codes(A,[115]).
cnt(A):- atom_codes(A,[122]).
cnt(A):- atom_codes(A,[643]).
cnt(A):- atom_codes(A,[658]).
cnt(A):- atom_codes(A,[108]).
cnt(A):- atom_codes(A,[633]).
cnt(A):- atom_codes(A,[106]).
cnt(A):- atom_codes(A,[119]).
cnt(A):- atom_codes(A,[104]).
cnt(A):- atom_codes(A,[105]).
cnt(A):- atom_codes(A,[618]).
cnt(A):- atom_codes(A,[101]).
cnt(A):- atom_codes(A,[230]).
cnt(A):- atom_codes(A,[117]).
cnt(A):- atom_codes(A,[650]).
cnt(A):- atom_codes(A,[111]).
cnt(A):- atom_codes(A,[097]).
cnt(A):- atom_codes(A,[601]).
cnt(A):- atom_codes(A,[652]).
lab(A):- atom_codes(A,[112]).
lab(A):- atom_codes(A,[098]).
lab(A):- atom_codes(A,[109]).
lab(A):- atom_codes(A,[102]).
lab(A):- atom_codes(A,[118]).
lab(A):- atom_codes(A,[119]).
alv(A):- atom_codes(A,[116]).
alv(A):- atom_codes(A,[100]).
alv(A):- atom_codes(A,[110]).
alv(A):- atom_codes(A,[115]).
alv(A):- atom_codes(A,[122]).
alv(A):- atom_codes(A,[108]).
alv(A):- atom_codes(A,[633]).
pal(A):- atom_codes(A,[643]).
pal(A):- atom_codes(A,[658]).
pal(A):- atom_codes(A,[269]).
pal(A):- atom_codes(A,[496]).
pal(A):- atom_codes(A,[633]).
pal(A):- atom_codes(A,[106]).
ant(A):- atom_codes(A,[112]).
ant(A):- atom_codes(A,[098]).
ant(A):- atom_codes(A,[109]).
ant(A):- atom_codes(A,[116]).
ant(A):- atom_codes(A,[100]).
ant(A):- atom_codes(A,[110]).
ant(A):- atom_codes(A,[102]).
ant(A):- atom_codes(A,[118]).
ant(A):- atom_codes(A,[952]).
ant(A):- atom_codes(A,[240]).
ant(A):- atom_codes(A,[115]).
ant(A):- atom_codes(A,[122]).
ant(A):- atom_codes(A,[108]).
ant(A):- atom_codes(A,[633]).
vel(A):- atom_codes(A,[107]).
vel(A):- atom_codes(A,[103]).
vel(A):- atom_codes(A,[331]).
vel(A):- atom_codes(A,[119]).
cor(A):- atom_codes(A,[116]).
cor(A):- atom_codes(A,[100]).
cor(A):- atom_codes(A,[110]).
cor(A):- atom_codes(A,[952]).
cor(A):- atom_codes(A,[240]).
cor(A):- atom_codes(A,[115]).
cor(A):- atom_codes(A,[122]).
cor(A):- atom_codes(A,[643]).
cor(A):- atom_codes(A,[658]).
cor(A):- atom_codes(A,[269]).
cor(A):- atom_codes(A,[496]).
cor(A):- atom_codes(A,[108]).
cor(A):- atom_codes(A,[633]).
cor(A):- atom_codes(A,[106]).
sib(A):- atom_codes(A,[115]).
sib(A):- atom_codes(A,[122]).
sib(A):- atom_codes(A,[643]).
sib(A):- atom_codes(A,[658]).
sib(A):- atom_codes(A,[269]).
sib(A):- atom_codes(A,[496]).
hih(A):- atom_codes(A,[105]).
hih(A):- atom_codes(A,[618]).
hih(A):- atom_codes(A,[117]).
hih(A):- atom_codes(A,[650]).
mid(A):- atom_codes(A,[101]).
mid(A):- atom_codes(A,[111]).
mid(A):- atom_codes(A,[601]).
mid(A):- atom_codes(A,[652]).
low(A):- atom_codes(A,[230]).
low(A):- atom_codes(A,[097]).
bck(A):- atom_codes(A,[117]).
bck(A):- atom_codes(A,[650]).
bck(A):- atom_codes(A,[111]).
bck(A):- atom_codes(A,[097]).
ctr(A):- atom_codes(A,[601]).
